### PR TITLE
generalize for using react-script-x with other plugins

### PR DESCRIPTION
**Pull request by Deviad**
Hello,
I made a little modification that I feel is needed. 
I wanted to use Typescript and your plugin works just well.

This is what I have in my package.json

```"react-scripts-x": {
    "postcss": [
      {
        "name": "postcss-custom-properties",
        "config": {
          "preserve": true
        }
      },
      {
        "name": "autoprefixer"
      },
      {
        "name": "postcss-calc"
      },
      {
        "name": "postcss-inline-svg",
        "config": {
          "path": "public/images"
        }
      },
      {
        "name": "precss"
      }
    ],
    "ts-loader": {
      "mode": "development",
      "devtool": "inline-source-map",
      "entry": "./src/index.ts",
      "output": {
        "filename": "bundle.js"
      },
      "resolve": {
        "extensions": [
          ".ts",
          ".tsx",
          ".js"
        ]
      },
      "module": {
        "rules": [
          {
            "test": "/\\.tsx?$/",
            "loader": "ts-loader"
          }
        ]
      }
    }
  },```


I don't have any errors so far, I also debugged to see if any data is actually received passed to the involved function.
Could you please confirm that it is ok?

### CODE REVIEW

**Comment by mihhail-lapushkin** [comment]
Thanks!
I will have a look at it somewhere next week.

**Comment by Deviad** [comment]
I have found the best way to load typescript is using react-scripts-ts and then loading postcss on top of that.
I have implemented a way to determine which one of the two (react-scripts-ts or react-scripts) should be used and set the paths accordingly.

**Comment by mihhail-lapushkin** [comment]
Had a quick first look.
Can you please leave the formatting as it was?
Right now the diff looks messy and it's hard to see what has actually changed.

**Comment by Ardhimas** [comment]
@mihhail-lapushkin looks to me like the only serious change he made was

```
+  [require.resolve(`${reactScriptName}/bin/${reactScriptName}`)].concat(args),
```

**Comment by Deviad** [comment]
I have added the possibility at start to check if create-react-app-typescript is installed so that, if it is, react-scripts-x will use that webpack config file to apply its modifications.

Reproducing all the changes, as I meant at first, that create-react-app-typescript applies to CRA's bundle inside react-scripts-x was too much time consuming and also a non-sense. When I started I had no idea there were so many changes to add. 

```
+if (path.dirname(require.resolve('react-scripts-ts/package'))) {
+  reactScriptsDir = path.dirname(require.resolve('react-scripts-ts/package'));
+  reactScriptName = 'react-scripts-ts';
+} else if (path.dirname(require.resolve('react-scripts/package'))) {
+  reactScriptsDir = path.dirname(require.resolve('react-scripts/package'));
+  reactScriptName = 'react-scripts';
+} else {
+  throw new Error('react-scripts package not found');
+}
```

**Comment by mihhail-lapushkin** [comment]
Thank you for your effort, but I would say that this is too specific. This project is about making changes to `react-scripts`. IMO contributing something to `react-scripts-ts` would make more sense in this case.

**Pull request closed without merging**
